<%@ Page Title="Good Hotel - Romtyper" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="Romtyper.aspx.cs" Inherits="Romtyper" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HovedBilde" Runat="Server">

    <div class="bildecontainer">
            <img src="pictures/korridor.png" alt="Bilde av vårt hotells korridorer" style="width:100%; height:auto; min-height: 500px;" />
            <div class="innledning">
                <p><h3>Våre <img class="logo" src="pictures/krone2.png" alt="Logo til Good Hotel" /> <span>Rom</span></h3> <br />
                Nedenfor får du en fin oversikt over våre vakre rom, velg hva som passer dine behov!
                    </p>
            </div>
        </div>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">

 <div class='kolonne'><h2>The Chinatown Single</h2><br><img src='pictures/romsingle.jpg' style='max-width:100%;' alt='Bilde av et av våre Chinatown Single rom'/><br><br /><p id='romtekst'>The Chinatown Single er det perfekte rom for deg som reiser alene. Rommet er utstyrt med minibar med ulike varianter av drikkevarer som faller enhver i smak, 65 tommer tv og våre King Size bed med fløyelsmyk sengetøy av ypperste kvalitet! Badet består av både dusj og badekar som standard, så her unner vi ingenting! Husk at daglig massasje er også inkludert i prisen samt frokost på rommet for den som har dårlig med tid. Dette rommet vil du garantert elske!<br><br></p><br><h4><b>Dette rommet inkluderer</b></h4><br><ul><li>Minibar</li><li>65 tommer 4k tv</li><li>King Size seng</li><li>Dusj og badekar</li><li>Daglig massasje</li><li>Frokost på rommet inkludert</li><li>Ypperlig for en person</li></ul><br /><b>Pris per natt: 50 000,- NOK</b><br /></div>
<div class='kolonne'><h2>The Dubai Double</h2><br><img src='pictures/romdouble.jpg' style='max-width:100%;' alt='Bilde av et av våre Dubai Double rom'/><br><br /><p id='romtekst'>The Dubai Double er det perfekte rom for det forelskede par på reise. Hvis et rom med Extra King Size bed av top kvalitet, dempende lys og høytalere utstyrt i tak og vegger hvor du kan spille den musikk du ønsker ikke faller i smak, vet ikke vi. Våre Dubai Double rom har eksklusive bad perfekt for to, dobbel dusj, doble vasker og sist men ikke minst boblebad på terassen med utsikt over byens fasade bør i hvertfall gjøre susen. Om dere ikke er nyforelsket vil dere bli det nå!<br></p><br><h4><b>Dette rommet inkluderer</b></h4><ul><li>Minibar</li><li>To King Size senger</li><li>Justerende lys med fargevalg</li><li>PA Anlegg for ypperlig musikk</li><li>65 tommer 4k tv</li><li>Dobbel dusj samt doble vasker</li><li>Terasse med boblebad og ypperlig utsikt</li><li>Ypperlig for to personer</li></ul><br /><b>Pris per natt: 100 000,- NOK</b><br /></div>
    <div class='kolonne'><h2>Le Royaume des Cieux</h2><br><img src='pictures/goodfrench.jpg' style='max-width:100%;' alt='Bilde av et av våre eksklusive fransk spesial rom'/><br><br /><p id='romtekst'>Går det ann å oppleve fransk kultur uten å måtte dra til kjærlighetens land? Da er Le Royaume des Cieux rommet for dere. Duften av forelskelse fyller rommet, og Paris er like rundt hjørnet. Med innebygd fontene og ekte fransk musikk i bakgrunn kan Frankrike virkelig oppleves her hos oss. Badet består av stor og dusj, stort badekar og doble vasker som standard. Om dere er to par på utskikk på noe uten det vanlige, er valget her. Bienvenue!<br><br></p><br><h4><b>Dette rommet inkluderer</b></h4><ul><li>Minibar med gratis påfyll</li><li>65 tommer 4k tv</li><li>Fire King Size senger</li><li>Stort bad med dusj og badekar</li><li>Innebygd fontene</li><li>Frokost på rommet inkludert</li></ul></div><b>Pris per natt: 200 000,- NOK</b><br /><br>
    <div class='kolonne'><h2>The Italian Job</h2><br /><img src='pictures/rompenthouse.jpg' style='max-width:100%;' alt='Bilde av et av våre eksklusive penthouses'/><br /><br /><p id='romtekst'>The Italian Job er for den som vet hva han vil ha. Toppen av kransekaka. Prikken over I&#39;en. Her er det verken mindre, heller mer. To etasjer, tre soverom, ett master bedroom, tre bad, to kjøkken, egen mini kinosal hvor ukens filmer spilles dagen lang. 360 grader med veranda, to boblebad. Egen bar kun utstyrt med de beste årganger og egen bartender på job KUN for deg. Daglig massasje og frokost på døren. Velkommen hjem, til ditt hjem<br><br><br><h4><b>Dette rommet inkluderer</b></h4><ul><li>Minibar med gratis påfyll</li><li>65 tommer 4k tv</li><li>To etasjer</li><li>Tre soverom + ett master bedroom</li><li>Tre bad inkludert dusj og badekar</li><li>To kjøkken</li><li>Egen mini kinosal</li><li>360 graders terasse med to boblebad</li><li>Daglig massasje</li><li>Frokost på rommet inkludert</li></ul></div><b>Pris per natt: 500 000,- NOK</b><br /><br>

</asp:Content>

